package duan.qlbn.ui;

import duan.qlbn.dao.ThongKeDAO;
import duan.qlbn.utils.XDate;
import java.awt.Frame;
import java.util.Date;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ThongKeJPanel extends javax.swing.JPanel {

    ThongKeDAO tkDAO = new ThongKeDAO();

    /**
     * Creates new form ThongKeJPanel
     */
    public ThongKeJPanel() {
        initComponents();
        doanhThuTheoNgay();
        soLuongHoaDonTheoNgay();
        soLuongKhachTheoNgay();
        luongSanPhamTheoNgay();
        doanhThuNgayTrongThang();
    }

    void doanhThuNgayTrongThang() {
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        model.setRowCount(0);

        List<Object[]> list = tkDAO.getDoanhThuNgayTrongThang();
        int i = 1;
        for (Object[] row : list) {
            model.addRow(new Object[]{i, row[0], row[1]});
            i++;
        }
    }

    void luongSanPhamTheoNam() {
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongSanPhamNam(ngay);

        for (Object[] row : list) {
            lblSanPham.setText(String.valueOf(row[0]));
        }
    }

    void luongSanPhamTheoThang() {
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongSanPhamThang(ngay);

        for (Object[] row : list) {
            lblSanPham.setText(String.valueOf(row[0]));
        }
    }

    void luongSanPhamTheoNgay() {
        lblSanPham.setText("");
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongSanPhamNgay(ngay);

        for (Object[] row : list) {
            lblSanPham.setText(String.valueOf(row[0]));
        }
    }

    void soLuongKhachTheoNam() {
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongKhachNam(ngay);

        for (Object[] row : list) {
            lblKhachHang.setText(String.valueOf(row[0]));
        }
    }

    void soLuongKhachTheoThang() {
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongKhachThang(ngay);

        for (Object[] row : list) {
            lblKhachHang.setText(String.valueOf(row[0]));
        }
    }

    void soLuongKhachTheoNgay() {
        lblKhachHang.setText("");
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongKhachNgay(ngay);

        for (Object[] row : list) {
            lblKhachHang.setText(String.valueOf(row[0]));
        }
    }

    void soLuongHoaDonTheoNam() {
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongHoaDonNam(ngay);

        for (Object[] row : list) {
            lblSoHoaDon.setText(String.valueOf(row[0]));
        }
    }

    void soLuongHoaDonTheoThang() {
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongHoaDonThang(ngay);

        for (Object[] row : list) {
            lblSoHoaDon.setText(String.valueOf(row[0]));
        }
    }

    void soLuongHoaDonTheoNgay() {
        lblSoHoaDon.setText("");
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getLuongHoaDonNgay(ngay);

        for (Object[] row : list) {
            lblSoHoaDon.setText(String.valueOf(row[0]));
        }
    }

    void doanhThuTheoNgay() {
        lblDoanhThu.setText("");
        String ngay = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getDoanhThuNgay(ngay);

        for (Object[] row : list) {
            lblDoanhThu.setText(String.valueOf(row[0]));
        }
    }

    void doanhThuTheoThang() {
        String thang = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getDoanhThuThang(thang);

        for (Object[] row : list) {
            lblDoanhThu.setText(String.valueOf(row[0]));
        }
    }

    void doanhThuTheoNam() {
        String nam = String.valueOf(java.time.LocalDate.now());
        List<Object[]> list = tkDAO.getDoanhThuNam(nam);

        for (Object[] row : list) {
            lblDoanhThu.setText(String.valueOf(row[0]));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblSoHoaDon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboThoiGian = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        pnlNen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jPanel2.setBackground(new java.awt.Color(142, 142, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/qlbn/icon/icons8-revenue-32.png"))); // NOI18N
        jLabel1.setText("Doanh Thu");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoanhThu.setText("00");
        jPanel2.add(lblDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("VND");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jPanel3.setBackground(new java.awt.Color(186, 123, 247));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/qlbn/icon/icons8-bill-32.png"))); // NOI18N
        jLabel3.setText("Số Hóa Đơn");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblSoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoHoaDon.setText("00");
        jPanel3.add(lblSoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/qlbn/icon/icons8-product-32.png"))); // NOI18N
        jLabel7.setText("Sản Phẩm");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSanPham.setText("00");
        jPanel4.add(lblSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel9.setText("Thời gian");

        cboThoiGian.setBackground(new java.awt.Color(0, 153, 255));
        cboThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm nay", "Tháng này", "Năm này" }));
        cboThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThoiGianActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(241, 208, 62));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/qlbn/icon/handshake.png"))); // NOI18N
        jLabel11.setText("Số Khách Hàng");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKhachHang.setText("00");
        jPanel6.add(lblKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pnlNen.setBackground(new java.awt.Color(255, 255, 255));
        pnlNen.setBorder(javax.swing.BorderFactory.createTitledBorder("Doanh thu các ngày trong tháng"));

        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Thời Gian", "Tổng Doanh Thu"
            }
        ));
        jScrollPane1.setViewportView(tblDoanhThu);
        if (tblDoanhThu.getColumnModel().getColumnCount() > 0) {
            tblDoanhThu.getColumnModel().getColumn(0).setResizable(false);
            tblDoanhThu.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout pnlNenLayout = new javax.swing.GroupLayout(pnlNen);
        pnlNen.setLayout(pnlNenLayout);
        pnlNenLayout.setHorizontalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlNenLayout.setVerticalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/qlbn/icon/icons8-analytics-33.png"))); // NOI18N
        jButton1.setText("Biểu Đồ Doanh Thu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cboThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThoiGianActionPerformed
        // TODO add your handling code here:
        if (cboThoiGian.getSelectedIndex() == 0) {
            doanhThuTheoNgay();
            soLuongHoaDonTheoNgay();
            soLuongKhachTheoNgay();
            luongSanPhamTheoNgay();
        }
        if (cboThoiGian.getSelectedIndex() == 1) {
            doanhThuTheoThang();
            soLuongHoaDonTheoThang();
            soLuongKhachTheoThang();
            luongSanPhamTheoThang();
        }
        if (cboThoiGian.getSelectedIndex() == 2) {
            doanhThuTheoNam();
            soLuongHoaDonTheoNam();
            soLuongKhachTheoNam();
            luongSanPhamTheoNam();
        }
    }//GEN-LAST:event_cboThoiGianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BieuDoDoanhThuJDialog dshd = new BieuDoDoanhThuJDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        dshd.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboThoiGian;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblSoHoaDon;
    private javax.swing.JPanel pnlNen;
    private javax.swing.JTable tblDoanhThu;
    // End of variables declaration//GEN-END:variables

}
